// export const products = [
// 	{
// 		id: 1,
// 		brand: "adidas",
// 		category: "woman",
// 		description:
// 			"Adidas knows what to wear! This time, it offers red wide-leg trousers with a beautiful floral motif, designed in collaboration with South African brand Thebe Magugu. This design will guarantee you a brilliant look and allow you to stand out on the town! You can also count on a high level of comfort. The lightweight material sits comfortably on the body, while the elasticated waistband with drawstring tie ensures a precise, individual fit. The trousers are made from 67% recycled material and are an environmentally friendly choice.",
// 		discount: true,
// 		images: [
// 			{ id: "1", url: "/products/woman-jeans-adidas-1.jpg" },
// 			{ id: "2", url: "/products/woman-jeans-adidas-2.jpg" },
// 			{ id: "3", url: "/products/woman-jeans-adidas-1.jpg" },
// 		],
// 		name: "adidas Originals PANTS",
// 		price: 100,
// 		reviews: 25,
// 		size: ["XS", "S", "M"],
// 		stars: 4.2,
// 		stock: 6,
// 	},
// 	{
// 		id: 1,
// 		brand: "adidas",
// 		category: "woman",
// 		description:
// 			"Adidas knows what to wear! This time, it offers red wide-leg trousers with a beautiful floral motif, designed in collaboration with South African brand Thebe Magugu. This design will guarantee you a brilliant look and allow you to stand out on the town! You can also count on a high level of comfort. The lightweight material sits comfortably on the body, while the elasticated waistband with drawstring tie ensures a precise, individual fit. The trousers are made from 67% recycled material and are an environmentally friendly choice.",
// 		discount: true,
// 		images: [
// 			{ id: "1", url: "/products/woman-jeans-adidas-1.jpg" },
// 			{ id: "2", url: "/products/woman-jeans-adidas-2.jpg" },
// 			{ id: "3", url: "/products/woman-jeans-adidas-2.jpg" },
// 		],
// 		name: "adidas Originals PANTS",
// 		price: 100,
// 		reviews: 25,
// 		size: ["XS", "S", "M"],
// 		stars: 4.2,
// 		stock: 6,
// 	},
// 	{
// 		id: 1,
// 		brand: "adidas",
// 		category: "woman",
// 		description:
// 			"Adidas knows what to wear! This time, it offers red wide-leg trousers with a beautiful floral motif, designed in collaboration with South African brand Thebe Magugu. This design will guarantee you a brilliant look and allow you to stand out on the town! You can also count on a high level of comfort. The lightweight material sits comfortably on the body, while the elasticated waistband with drawstring tie ensures a precise, individual fit. The trousers are made from 67% recycled material and are an environmentally friendly choice.",
// 		discount: true,
// 		images: [
// 			{ id: "1", url: "/products/woman-jeans-adidas-1.jpg" },
// 			{ id: "2", url: "/products/woman-jeans-adidas-2.jpg" },
// 			{ id: "3", url: "/products/woman-jeans-adidas-1.jpg" },
// 		],
// 		name: "adidas Originals PANTS",
// 		price: 100,
// 		reviews: 25,
// 		size: ["XS", "S", "M"],
// 		stars: 4.2,
// 		stock: 6,
// 	},
// 	{
// 		id: 1,
// 		brand: "adidas",
// 		category: "woman",
// 		description:
// 			"Adidas knows what to wear! This time, it offers red wide-leg trousers with a beautiful floral motif, designed in collaboration with South African brand Thebe Magugu. This design will guarantee you a brilliant look and allow you to stand out on the town! You can also count on a high level of comfort. The lightweight material sits comfortably on the body, while the elasticated waistband with drawstring tie ensures a precise, individual fit. The trousers are made from 67% recycled material and are an environmentally friendly choice.",
// 		discount: true,
// 		images: [
// 			{ id: "1", url: "/products/woman-jeans-adidas-1.jpg" },
// 			{ id: "2", url: "/products/woman-jeans-adidas-2.jpg" },
// 			{ id: "3", url: "/products/woman-jeans-adidas-2.jpg" },
// 		],
// 		name: "adidas Originals PANTS",
// 		price: 100,
// 		reviews: 25,
// 		size: ["XS", "S", "M"],
// 		stars: 4.2,
// 		stock: 6,
// 	},
// 	{
// 		id: 1,
// 		brand: "adidas",
// 		category: "woman",
// 		description:
// 			"Adidas knows what to wear! This time, it offers red wide-leg trousers with a beautiful floral motif, designed in collaboration with South African brand Thebe Magugu. This design will guarantee you a brilliant look and allow you to stand out on the town! You can also count on a high level of comfort. The lightweight material sits comfortably on the body, while the elasticated waistband with drawstring tie ensures a precise, individual fit. The trousers are made from 67% recycled material and are an environmentally friendly choice.",
// 		discount: true,
// 		images: [
// 			{ id: "1", url: "/products/woman-jeans-adidas-1.jpg" },
// 			{ id: "2", url: "/products/woman-jeans-adidas-2.jpg" },
// 			{ id: "3", url: "/products/woman-jeans-adidas-2.jpg" },
// 		],
// 		name: "adidas Originals PANTS",
// 		price: 100,
// 		reviews: 25,
// 		size: ["XS", "S", "M"],
// 		stars: 4.2,
// 		stock: 6,
// 	},
// 	{
// 		id: 1,
// 		brand: "adidas",
// 		category: "woman",
// 		description:
// 			"Adidas knows what to wear! This time, it offers red wide-leg trousers with a beautiful floral motif, designed in collaboration with South African brand Thebe Magugu. This design will guarantee you a brilliant look and allow you to stand out on the town! You can also count on a high level of comfort. The lightweight material sits comfortably on the body, while the elasticated waistband with drawstring tie ensures a precise, individual fit. The trousers are made from 67% recycled material and are an environmentally friendly choice.",
// 		discount: true,
// 		images: [
// 			{ id: "1", url: "/products/woman-jeans-adidas-1.jpg" },
// 			{ id: "2", url: "/products/woman-jeans-adidas-2.jpg" },
// 			{ id: "3", url: "/products/woman-jeans-adidas-2.jpg" },
// 		],
// 		name: "adidas Originals PANTS",
// 		price: 100,
// 		reviews: 25,
// 		size: ["XS", "S", "M"],
// 		stars: 4.2,
// 		stock: 6,
// 	},
// 	{
// 		id: 1,
// 		brand: "adidas",
// 		category: "woman",
// 		description:
// 			"Adidas knows what to wear! This time, it offers red wide-leg trousers with a beautiful floral motif, designed in collaboration with South African brand Thebe Magugu. This design will guarantee you a brilliant look and allow you to stand out on the town! You can also count on a high level of comfort. The lightweight material sits comfortably on the body, while the elasticated waistband with drawstring tie ensures a precise, individual fit. The trousers are made from 67% recycled material and are an environmentally friendly choice.",
// 		discount: true,
// 		images: [
// 			{ id: "1", url: "/products/woman-jeans-adidas-1.jpg" },
// 			{ id: "2", url: "/products/woman-jeans-adidas-2.jpg" },
// 			{ id: "3", url: "/products/woman-jeans-adidas-2.jpg" },
// 		],
// 		name: "adidas Originals PANTS",
// 		price: 100,
// 		reviews: 25,
// 		size: ["XS", "S", "M"],
// 		stars: 4.2,
// 		stock: 6,
// 	},
// 	{
// 		id: 1,
// 		brand: "adidas",
// 		category: "woman",
// 		description:
// 			"Adidas knows what to wear! This time, it offers red wide-leg trousers with a beautiful floral motif, designed in collaboration with South African brand Thebe Magugu. This design will guarantee you a brilliant look and allow you to stand out on the town! You can also count on a high level of comfort. The lightweight material sits comfortably on the body, while the elasticated waistband with drawstring tie ensures a precise, individual fit. The trousers are made from 67% recycled material and are an environmentally friendly choice.",
// 		discount: true,
// 		images: [
// 			{ id: "1", url: "/products/woman-jeans-adidas-1.jpg" },
// 			{ id: "2", url: "/products/woman-jeans-adidas-2.jpg" },
// 			{ id: "3", url: "/products/woman-jeans-adidas-2.jpg" },
// 		],
// 		name: "adidas Originals PANTS",
// 		price: 100,
// 		reviews: 25,
// 		size: ["XS", "S", "M"],
// 		stars: 4.2,
// 		stock: 6,
// 	},
// ];
export const products = [
	{
		category: "kids",
		stock: 6,
		stars: 3.5,
		description:
			"The streets have never been so colourful! The Adicolor Track trousers bring every set to life! Their energetic design and relaxed, casual cut are the elements that immediately catch the eye. The elastic waistband fits snugly around the waist. The soft, tactile fabric charms with its delicate sheen and keeps its impeccable appearance even after repeated use. The details also turn the look on its head! The Trefoil logo adorns one of the legs and accentuates the brand's distinctive DNA.",
		images: [
			{
				id: "1",
				url: "/products/kids-jeans-adidas-1",
			},
			{
				url: "/products/kids-jeans-adidas-2",
				id: "2",
			},
			{
				id: "3",
				url: "/products/kids-jeans-adidas-3",
			},
		],
		brand: "adidas",
		name: "Adidas SST Track Pants",
		price: 205.99,
		reviews: 61,
		discount: false,
		size: ["M"],
		id: "Hz3APFJvf1nRkqOF6hf1",
	},
	{
		price: 89.99,
		reviews: 84,
		discount: true,
		category: "women",
		images: [
			{
				id: "1",
				url: "/products/woman-tshirt-nike-1",
			},
			{
				id: "2",
				url: "/products/woman-tshirt-nike-2",
			},
			{
				url: "/products/woman-tshirt-nike-3",
				id: "3",
			},
		],
		stock: 6,
		brand: "nike",
		size: ["S", "XL"],
		name: "Nike T-Shirt Essential",
		stars: 4.2,
		description:
			"A versatile T-shirt in streetwear style from the Nike brand. The model has a shortened cut and lowered shoulder line. Cotton fabric sits comfortably on the body and allows the skin to breathe. A contrasting brand logo adorns the front.",
		id: "KsSEMcpSZ9qXcwlTFezv",
	},
	{
		description:
			"Opt for the New Balance brand for everyday styling and choose the MS237 line of sneakers. The shoe features an upper made of a combination of suede leather and textile mesh. The brand's tradition is recalled by the 'N' logo, this time in a more dynamic version. The soft cushioning is another highlight, as is the springy and well-gripped sole.",
		name: "New Balance Sneakers 237",
		stars: 4,
		discount: false,
		price: 469.99,
		reviews: 17,
		size: ["L", "XL"],
		stock: 5,
		images: [
			{
				url: "/products/man-sneakers-newbalance-1",
				id: "1",
			},
			{
				id: "2",
				url: "/products/man-sneakers-newbalance-2",
			},
			{
				id: "3",
				url: "/products/man-sneakers-newbalance-3",
			},
		],
		category: "men",
		brand: "new balance",
		id: "Ylqj0NHenBJQtzRwz07i",
	},
	{
		category: "men",
		reviews: 108,
		stock: 8,
		size: ["M", "L", "XL"],
		description:
			"A T-shirt from the adidas brand that will always be on trend. The navy blue colour scheme is complemented by the iconic 1972 logo in white. The entire garment is made from pleasant-to-touch cotton and maintained in a regular cut. As a result, the T-shirt provides all-day comfort and allows the skin to breathe. The model will be the perfect addition to everyday streetwear sets.",
		brand: "adidas",
		price: 169.99,
		stars: 2,
		name: "Adidas T-Shirt Treofil",
		discount: true,
		images: [
			{
				url: "/products/man-tshirt-adidas-1",
				id: "1",
			},
			{
				id: "2",
				url: "/products/man-tshirt-adidas-2",
			},
			{
				url: "/products/man-tshirt-adidas-3",
				id: "3",
			},
		],
		id: "bvKOFC6RsKusU1KPxBwt",
	},
];

export const cartProducts = [
	{
		id: "bvKOFC6RsKusU1KPxBwtS",
		size: "S",
		amount: 3,
		name: "Adidas T-Shirt Treofil",
		image: "/products/man-tshirt-adidas-3",
		price: 69.99,
		max: 6,
	},
	{
		id: "bvKOFC6RsKusU1KPxBwtM",
		size: "M",
		amount: 4,
		name: "Nike T-Shirt Essential",
		image: "/products/man-sneakers-newbalance-3",
		price: 169.99,
		max: 8,
	},
	{
		id: "bvKOFC6RsKusU1KPxBwtL",
		size: "L",
		amount: 5,
		name: "Adidas SST Track Pants",
		image: "/products/woman-tshirt-nike-3",
		price: 1169.99,
		max: 10,
	},
];
