export const products = [
	{
		id: 1,
		brand: "adidas",
		category: "woman",
		description:
			"Adidas knows what to wear! This time, it offers red wide-leg trousers with a beautiful floral motif, designed in collaboration with South African brand Thebe Magugu. This design will guarantee you a brilliant look and allow you to stand out on the town! You can also count on a high level of comfort. The lightweight material sits comfortably on the body, while the elasticated waistband with drawstring tie ensures a precise, individual fit. The trousers are made from 67% recycled material and are an environmentally friendly choice.",
		discount: true,
		images: [
			{ id: "1", url: "/products/woman-jeans-adidas-1.jpg" },
			{ id: "2", url: "/products/woman-jeans-adidas-2.jpg" },
			{ id: "3", url: "/products/woman-jeans-adidas-3.jpg" },
		],
		name: "adidas Originals PANTS",
		price: 100,
		reviews: 25,
		size: ["XS", "S", "M"],
		stars: 4.2,
		stock: 6,
	},
	{
		id: 1,
		brand: "adidas",
		category: "woman",
		description:
			"Adidas knows what to wear! This time, it offers red wide-leg trousers with a beautiful floral motif, designed in collaboration with South African brand Thebe Magugu. This design will guarantee you a brilliant look and allow you to stand out on the town! You can also count on a high level of comfort. The lightweight material sits comfortably on the body, while the elasticated waistband with drawstring tie ensures a precise, individual fit. The trousers are made from 67% recycled material and are an environmentally friendly choice.",
		discount: true,
		images: [
			{ id: "1", url: "/products/woman-jeans-adidas-1.jpg" },
			{ id: "2", url: "/products/woman-jeans-adidas-2.jpg" },
			{ id: "3", url: "/products/woman-jeans-adidas-3.jpg" },
		],
		name: "adidas Originals PANTS",
		price: 100,
		reviews: 25,
		size: ["XS", "S", "M"],
		stars: 4.2,
		stock: 6,
	},
	{
		id: 1,
		brand: "adidas",
		category: "woman",
		description:
			"Adidas knows what to wear! This time, it offers red wide-leg trousers with a beautiful floral motif, designed in collaboration with South African brand Thebe Magugu. This design will guarantee you a brilliant look and allow you to stand out on the town! You can also count on a high level of comfort. The lightweight material sits comfortably on the body, while the elasticated waistband with drawstring tie ensures a precise, individual fit. The trousers are made from 67% recycled material and are an environmentally friendly choice.",
		discount: true,
		images: [
			{ id: "1", url: "/products/woman-jeans-adidas-1.jpg" },
			{ id: "2", url: "/products/woman-jeans-adidas-2.jpg" },
			{ id: "3", url: "/products/woman-jeans-adidas-3.jpg" },
		],
		name: "adidas Originals PANTS",
		price: 100,
		reviews: 25,
		size: ["XS", "S", "M"],
		stars: 4.2,
		stock: 6,
	},
	{
		id: 1,
		brand: "adidas",
		category: "woman",
		description:
			"Adidas knows what to wear! This time, it offers red wide-leg trousers with a beautiful floral motif, designed in collaboration with South African brand Thebe Magugu. This design will guarantee you a brilliant look and allow you to stand out on the town! You can also count on a high level of comfort. The lightweight material sits comfortably on the body, while the elasticated waistband with drawstring tie ensures a precise, individual fit. The trousers are made from 67% recycled material and are an environmentally friendly choice.",
		discount: true,
		images: [
			{ id: "1", url: "/products/woman-jeans-adidas-1.jpg" },
			{ id: "2", url: "/products/woman-jeans-adidas-2.jpg" },
			{ id: "3", url: "/products/woman-jeans-adidas-3.jpg" },
		],
		name: "adidas Originals PANTS",
		price: 100,
		reviews: 25,
		size: ["XS", "S", "M"],
		stars: 4.2,
		stock: 6,
	},
	{
		id: 1,
		brand: "adidas",
		category: "woman",
		description:
			"Adidas knows what to wear! This time, it offers red wide-leg trousers with a beautiful floral motif, designed in collaboration with South African brand Thebe Magugu. This design will guarantee you a brilliant look and allow you to stand out on the town! You can also count on a high level of comfort. The lightweight material sits comfortably on the body, while the elasticated waistband with drawstring tie ensures a precise, individual fit. The trousers are made from 67% recycled material and are an environmentally friendly choice.",
		discount: true,
		images: [
			{ id: "1", url: "http://unsplash.it/200/300" },
			{ id: "2", url: "http://unsplash.it/200/300" },
			{ id: "3", url: "http://unsplash.it/200/300" },
		],
		name: "adidas Originals PANTS",
		price: 100,
		reviews: 25,
		size: ["XS", "S", "M"],
		stars: 4.2,
		stock: 6,
	},
	{
		id: 1,
		brand: "adidas",
		category: "woman",
		description:
			"Adidas knows what to wear! This time, it offers red wide-leg trousers with a beautiful floral motif, designed in collaboration with South African brand Thebe Magugu. This design will guarantee you a brilliant look and allow you to stand out on the town! You can also count on a high level of comfort. The lightweight material sits comfortably on the body, while the elasticated waistband with drawstring tie ensures a precise, individual fit. The trousers are made from 67% recycled material and are an environmentally friendly choice.",
		discount: true,
		images: [
			{ id: "1", url: "http://unsplash.it/200/300" },
			{ id: "2", url: "http://unsplash.it/200/300" },
			{ id: "3", url: "http://unsplash.it/200/300" },
		],
		name: "adidas Originals PANTS",
		price: 100,
		reviews: 25,
		size: ["XS", "S", "M"],
		stars: 4.2,
		stock: 6,
	},
	{
		id: 1,
		brand: "adidas",
		category: "woman",
		description:
			"Adidas knows what to wear! This time, it offers red wide-leg trousers with a beautiful floral motif, designed in collaboration with South African brand Thebe Magugu. This design will guarantee you a brilliant look and allow you to stand out on the town! You can also count on a high level of comfort. The lightweight material sits comfortably on the body, while the elasticated waistband with drawstring tie ensures a precise, individual fit. The trousers are made from 67% recycled material and are an environmentally friendly choice.",
		discount: true,
		images: [
			{ id: "1", url: "http://unsplash.it/200/300" },
			{ id: "2", url: "http://unsplash.it/200/300" },
			{ id: "3", url: "http://unsplash.it/200/300" },
		],
		name: "adidas Originals PANTS",
		price: 100,
		reviews: 25,
		size: ["XS", "S", "M"],
		stars: 4.2,
		stock: 6,
	},
	{
		id: 1,
		brand: "adidas",
		category: "woman",
		description:
			"Adidas knows what to wear! This time, it offers red wide-leg trousers with a beautiful floral motif, designed in collaboration with South African brand Thebe Magugu. This design will guarantee you a brilliant look and allow you to stand out on the town! You can also count on a high level of comfort. The lightweight material sits comfortably on the body, while the elasticated waistband with drawstring tie ensures a precise, individual fit. The trousers are made from 67% recycled material and are an environmentally friendly choice.",
		discount: true,
		images: [
			{ id: "1", url: "http://unsplash.it/200/300" },
			{ id: "2", url: "http://unsplash.it/200/300" },
			{ id: "3", url: "http://unsplash.it/200/300" },
		],
		name: "adidas Originals PANTS",
		price: 100,
		reviews: 25,
		size: ["XS", "S", "M"],
		stars: 4.2,
		stock: 6,
	},
];
